package week3.feb27;

import java.math.BigInteger;
import java.util.ArrayList;
/*
22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 to100 and 2 to100*/
public class SequenceofPower2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		BigInteger result = new BigInteger("0");
		ArrayList<BigInteger> a=new ArrayList<BigInteger>();
		for(BigInteger i = BigInteger.valueOf(2);i.compareTo(BigInteger.valueOf(100))<=0;i=i.add(BigInteger.ONE))
		{
			for(int j=2;j<=100;j++)
			{
				result=i.pow(j);
				if(!a.contains(result))
				{
					a.add(result);
				}
			}
		}
		System.out.println(a.size());
	}

}
