package week2.feb20;
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *  By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/

public class FibonacciSumofEvenValue {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		long number1 = 1;
		long number2 = 2;
		long range = 4000000;
		long sum = 0, sum1 = 2;
		for (long i = 0; i <= range; i++) {
			sum = number1 + number2;
			number1 = number2;
			number2 = sum;
			if (sum % 2 == 0) {
				sum1 = sum1 + sum;

			}
			if (sum > 4000000) {
				break;
			}

		}
		System.out.println(sum1);
	}

}
